tag_locations:
  [
    {id: 0, x: 0, y: 0, z: 0, qx: 0, qy: 0, qz: 0, qw: 1},
    {id: 1, x: 5, y: 5, z: 0, qx: 0, qy: 0, qz: 0, qw: 1},
    {id: 7, x: 1.191, y: 0.568, z: 0.086, qx: 0.523, qy: -0.390, qz: -0.455, qw: 0.606},
    {id: 8, x: 0.873, y: -1.957, z: 0.086, qx: 0.055, qy: 0.658, qz: 0.749, qw: 0.063}
  ]

